# ljeutil - a utility library which adds many different default gmod functions implemented in lua, all of which are optimised

[script]
name = "ljeutil"
version = "1.0.0"
author = "Eyoko1"
dependencies = []
